### ISSUE TITLE
Enhancement: save the preview as html

### ISSUE THREAD

**Issue by Abdelkrim** [wboka/vscode-rst2html#7]
to whom it may concern,
I have installed reStructuredText 2 HTML, it works fine.

Now, I would like to 

1. store the preview as an HTML file.
2. the HTML should embed the CSS

How could I do this?

Kind regards,
Abdelkrim

**Comment by wboka** [comment]
Hello,

I will look into adding this as a feature.

**Comment by wboka** [comment]
Actually, I don't use the plugin and it's not worth my time to develop and maintain it. Feel free to fork the repo.
